name: Serwisomat Workflow

on:
  workflow_dispatch:
    inputs:
      customer_email:
        description: 'Email klienta'
        required: true
      device_description:
        description: 'Opis urządzenia'
        required: true

jobs:
  process_repair:
    runs-on: ubuntu-latest
    steps:
      - name: Zgłoszenie naprawy
        run: |
             echo "Zgłoszenie przyjęte. Klient: ${{ github.event.inputs.customer_email }}, Urządzenie: ${{ github.event.inputs.device_description }}. Wysyłanie SMS z potwierdzeniem przyjęcia zgłoszenia."

      - name: Przyjęcie urządzenia do serwisu
        run: echo "Urządzenie przyjęte do serwisu. Wysyłanie SMS z informacją o przyjęciu urządzenia do serwisu."

      - name: Diagnoza urządzenia
        run: echo "Diagnoza urządzenia w toku. Wysyłanie SMS z informacją o rozpoczęciu diagnozy."

      - name: Wycena naprawy
        run: echo "Wycena naprawy przesłana do klienta. Wysyłanie SMS z wyceną i prośbą o potwierdzenie."

      - name: Oczekiwanie na decyzję klienta
        run: echo "Oczekiwanie na decyzję klienta. Wysyłanie SMS z przypomnieniem o konieczności akceptacji wyceny."

      - name: Naprawa urządzenia
        run: echo "Decyzja pozytywna. Naprawa urządzenia w toku. Wysyłanie SMS z informacją o rozpoczęciu naprawy."

      - name: Powrót do serwisomatu
        run: echo "Urządzenie naprawione. Wysyłanie SMS z informacją o zakończeniu naprawy i gotowości do odbioru."

      - name: Odbiór przez klienta
        run: echo "Urządzenie odebrane przez klienta. Wysyłanie SMS z podziękowaniem za skorzystanie z usług."
