name: Serwisomat Workflow

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Imię i nazwisko klienta'
        required: true
      customer_phone:
        description: 'Numer telefonu klienta'
        required: true
      device_description:
        description: 'Marka oraz model urządzenia'
        required: true
      device_serial_number:
        description: 'Numer seryjny urządzenia'
        required: true
      issue_description:
        description: 'Opis Usterki'
        required: true

jobs:
  process_repair:
    runs-on: ubuntu-latest
    steps:
      - name: Zgłoszenie naprawy
        run: |
              echo "Zgłoszenie od klienta: ${{ github.event.inputs.customer_name }}. Kontakt telefoniczny: ${{ github.event.inputs.customer_phone }}. Urządzenie: ${{ github.event.inputs.device_description }}, numer seryjny: ${{ github.event.inputs.device_serial_number }}. Opis usterki: ${{ github.event.inputs.issue_description }}."

      - name: Przyjęcie urządzenia
        run: echo "Urządzenie przyjęte do serwisu."

      - name: Diagnoza
        run: echo "Rozpoczynamy diagnozę urządzenia."

      - name: Wycena naprawy
        run: echo "Przygotowujemy wycenę naprawy."

      - name: Informacja o wycenie
        run: echo "Informacja o wycenie została przesłana do klienta."

      - name: Oczekiwanie na decyzję klienta
        run: echo "Czekamy na decyzję klienta dotyczącą naprawy."

      - name: Naprawa urządzenia
        run: echo "Urządzenie jest w trakcie naprawy."

      - name: Powrót do serwisomatu
        run: echo "Naprawa zakończona. Urządzenie gotowe do odbioru."

      - name: Odbiór przez klienta
        run: echo "Urządzenie zostało odebrane przez klienta. Dziękujemy za skorzystanie z naszych usług!"
